/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.File;
import javax.swing.JFileChooser;
/**
 *
 * @author 7304859
 */
public class WeatherFrame extends javax.swing.JFrame {
    JFileChooser fc;
    /**
     * Creates new form WeatherFrame
     */
    public WeatherFrame() {
        initComponents();
        fc = new JFileChooser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        WeatherMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        OpenMenuItem = new javax.swing.JMenuItem();
        QuitMenuItem = new javax.swing.JMenuItem();
        StatMenu = new javax.swing.JMenu();
        MeanTempMenuItem = new javax.swing.JMenuItem();
        HighTempMenuItem = new javax.swing.JMenuItem();
        LowTempMenuItem = new javax.swing.JMenuItem();
        MeanWindMenuItem = new javax.swing.JMenuItem();
        MaxWindMenuItem = new javax.swing.JMenuItem();
        PrevWindMenuItem = new javax.swing.JMenuItem();
        RainfallMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        FileMenu.setText("File");

        OpenMenuItem.setText("Open");
        OpenMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(OpenMenuItem);

        QuitMenuItem.setText("Quit");
        FileMenu.add(QuitMenuItem);

        WeatherMenuBar.add(FileMenu);

        StatMenu.setText("Statistics");

        MeanTempMenuItem.setText("Mean Temperature");
        StatMenu.add(MeanTempMenuItem);

        HighTempMenuItem.setText("High Temperature");
        StatMenu.add(HighTempMenuItem);

        LowTempMenuItem.setText("Low Temperature");
        StatMenu.add(LowTempMenuItem);

        MeanWindMenuItem.setText("Mean Wind Speed");
        StatMenu.add(MeanWindMenuItem);

        MaxWindMenuItem.setText("Max Wind Speed");
        StatMenu.add(MaxWindMenuItem);

        PrevWindMenuItem.setText("Prevailing Wind Direction");
        StatMenu.add(PrevWindMenuItem);

        RainfallMenuItem.setText("Rainfall");
        StatMenu.add(RainfallMenuItem);

        WeatherMenuBar.add(StatMenu);

        setJMenuBar(WeatherMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenMenuItemActionPerformed
        // TODO add your handling code here:
        int returnVal = fc.showOpenDialog(this);
        
        if ( returnVal == JFileChooser.APPROVE_OPTION )
        {
            File file = fc.getSelectedFile();
            //This is where a real application would open the file.
            System.out.println("Opening: " + file.getAbsoluteFile() + ".");
        }
        else
        {
            System.out.println( "Open command cancelled by user.\n" );
        }
    }//GEN-LAST:event_OpenMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeatherFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem HighTempMenuItem;
    private javax.swing.JMenuItem LowTempMenuItem;
    private javax.swing.JMenuItem MaxWindMenuItem;
    private javax.swing.JMenuItem MeanTempMenuItem;
    private javax.swing.JMenuItem MeanWindMenuItem;
    private javax.swing.JMenuItem OpenMenuItem;
    private javax.swing.JMenuItem PrevWindMenuItem;
    private javax.swing.JMenuItem QuitMenuItem;
    private javax.swing.JMenuItem RainfallMenuItem;
    private javax.swing.JMenu StatMenu;
    private javax.swing.JMenuBar WeatherMenuBar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
